services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  backend:
    image: raynersim/backend:v1.0
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXP_TIME=${JWT_EXP_TIME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_EC2_HOST=${FRONTEND_EC2_HOST}
    depends_on:
      - db

  frontend:
    image: raynersim/frontend:v1.0
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
     - NEXT_PUBLIC_BACKEND_EC2_HOST=${NEXT_PUBLIC_BACKEND_EC2_HOST}
    depends_on:
      - backend

  scrapper:
    image: raynersim/scrapper:v1.0
    restart: always
    environment:
      - RDS_ENDPOINT=db
      - RDS_PORT=5432
      - RDS_USERNAME=${DB_USER}
      - RDS_PASSWORD=${DB_PASSWORD}
      - RDS_DBNAME=${DB_NAME}
    depends_on:
      - db

volumes:
  postgres_data: